const uiStrings_en = {
  // Page Title
  page_title: "Makemon Character Maker +",

  // UI Elements
  themeLight: "Light",
  themeDark: "Dark",
  themeAmoled: "AMOLED",
  changeBgButton: "Change Background",
  toggleBlur: "Blur",
  toggleFrostedGlass: "Glass",

  // Randomizer Buttons
  randomizeAllButton: "Randomize",
  randomizeBodyColorButton: "Randomize Body Color",

  // Color Picker
  customColorPickerTitle: "Custom Color",
  applyCustomColor: "Apply",
  redLabel: "R:",
  greenLabel: "G:",
  blueLabel: "B:",

  // Header Image Alt Text
  headerImageAlt: "Makemon Character Maker",

  // Section Headers
  sectionHeaderBaseBody: "Body",
  sectionHeaderBackParts: "Back",
  sectionHeaderEyes: "Eyes",
  sectionHeaderNose: "Nose",
  sectionHeaderMouth: "Mouth",
  sectionHeaderEyebrows: "Eyebrows",
  sectionHeaderHair: "Hair",
  sectionHeaderOutfit: "Outfit",
  sectionHeaderAccessories: "Accessories",
  sectionHeaderOptions: "Extras",

  // Alt Texts
  // Body
  alt_fene_mimi: "Fene Body",
  alt_neko_mimi: "Cat Body",
  alt_inu_mimi: "Dog Body",
  alt_tare_inu_mimi: "Droopy Dog Body",
  alt_usa_mimi: "Rabbit Body",
  alt_tare_usa_mimi: "Droopy Rabbit Body",
  alt_meri_mimi: "Sheep Body",
  alt_uma_mimi: "Horse Body",
  alt_moko_mimi: "Moko Body",
  alt_kuma_mimi: "Bear Body",
  alt_dora_mimi: "Dragon Body",
  alt_upa_mimi: "Upa Body",

  // Back
  alt_fene_shippo: "Fene Tail",
  alt_neko_shippo: "Cat Tail",
  alt_inu_shippo: "Dog Tail",
  alt_moko_shippo: "Moko Tail",
  alt_uru_shippo: "Wolf Tail",
  alt_shima_naga_shippo: "Striped Long Tail",
  alt_dora_shippo: "Dragon Tail",
  alt_meri_you_moko: "Sheep Moko",
  alt_tategami: "Mane",
  alt_kinpatsu_shippo: "Blonde Tail",
  alt_ginpatsu_shippo: "Silver Tail",
  alt_enjeru: "Angel",
  alt_debiru: "Devil",
  alt_yousei: "Fairy",

  // Eyes
  alt_patchiri_mizuiro: "Wide Eyes (Light Blue)",
  alt_patchiri_ao: "Wide Eyes (Blue)",
  alt_patchiri_pinku: "Wide Eyes (Pink)",
  alt_patchiri_aka: "Wide Eyes (Red)",
  alt_patchiri_kimidori: "Wide Eyes (Lime)",
  alt_patchiri_kiiro: "Wide Eyes (Yellow)",
  alt_patchiri_shirubaa: "Wide Eyes (Silver)",
  alt_kurikuri_mizuiro: "Round Eyes (Light Blue)",
  alt_kurikuri_ao: "Round Eyes (Blue)",
  alt_kurikuri_pinku: "Round Eyes (Pink)",
  alt_kurikuri_aka: "Round Eyes (Red)",
  alt_kurikuri_kimidori: "Round Eyes (Lime)",
  alt_kurikuri_kiiro: "Round Eyes (Yellow)",
  alt_kurikuri_shirubaa: "Round Eyes (Silver)",
  alt_goshikku_mizuiro: "Gothic Eyes (Light Blue)",
  alt_goshikku_ao: "Gothic Eyes (Blue)",
  alt_goshikku_pinku: "Gothic Eyes (Pink)",
  alt_goshikku_aka: "Gothic Eyes (Red)",
  alt_goshikku_kimidori: "Gothic Eyes (Lime)",
  alt_goshikku_kiiro: "Gothic Eyes (Yellow)",
  alt_goshikku_shirubaa: "Gothic Eyes (Silver)",
  alt_donguri_mizuiro: "Acorn Eyes (Light Blue)",
  alt_donguri_ao: "Acorn Eyes (Blue)",
  alt_donguri_pinku: "Acorn Eyes (Pink)",
  alt_donguri_aka: "Acorn Eyes (Red)",
  alt_donguri_kimidori: "Acorn Eyes (Lime)",
  alt_donguri_kiiro: "Acorn Eyes (Yellow)",
  alt_donguri_shirubaa: "Acorn Eyes (Silver)",
  alt_tare_mizuiro: "Droopy Eyes (Light Blue)",
  alt_tare_ao: "Droopy Eyes (Blue)",
  alt_tare_pinku: "Droopy Eyes (Pink)",
  alt_tare_aka: "Droopy Eyes (Red)",
  alt_tare_kimidori: "Droopy Eyes (Lime)",
  alt_tare_kiiro: "Droopy Eyes (Yellow)",
  alt_tare_shirubaa: "Droopy Eyes (Silver)",
  alt_jito_mizuiro: "Jito Eyes (Light Blue)",
  alt_jito_ao: "Jito Eyes (Blue)",
  alt_jito_pinku: "Jito Eyes (Pink)",
  alt_jito_aka: "Jito Eyes (Red)",
  alt_jito_kimidori: "Jito Eyes (Lime)",
  alt_jito_kiiro: "Jito Eyes (Yellow)",
  alt_jito_shirubaa: "Jito Eyes (Silver)",
  alt_juerii_mizuiro: "Jewel Eyes (Light Blue)",
  alt_juerii_ao: "Jewel Eyes (Blue)",
  alt_juerii_pinku: "Jewel Eyes (Pink)",
  alt_juerii_aka: "Jewel Eyes (Red)",
  alt_juerii_kimidori: "Jewel Eyes (Lime)",
  alt_juerii_kiiro: "Jewel Eyes (Yellow)",
  alt_juerii_shirubaa: "Jewel Eyes (Silver)",
  alt_kuuru_mizuiro: "Cool Eyes (Light Blue)",
  alt_kuuru_ao: "Cool Eyes (Blue)",
  alt_kuuru_pinku: "Cool Eyes (Pink)",
  alt_kuuru_aka: "Cool Eyes (Red)",
  alt_kuuru_kimidori: "Cool Eyes (Lime)",
  alt_kuuru_kiiro: "Cool Eyes (Yellow)",
  alt_kuuru_shirubaa: "Cool Eyes (Silver)",
  alt_tsun_mizuiro: "Tsun Eyes (Light Blue)",
  alt_tsun_ao: "Tsun Eyes (Blue)",
  alt_tsun_pinku: "Tsun Eyes (Pink)",
  alt_tsun_aka: "Tsun Eyes (Red)",
  alt_tsun_kimidori: "Tsun Eyes (Lime)",
  alt_tsun_kiiro: "Tsun Eyes (Yellow)",
  alt_tsun_shirubaa: "Tsun Eyes (Silver)",
  alt_tsuri_mizuiro: "Tsuri Eyes (Light Blue)",
  alt_tsuri_ao: "Tsuri Eyes (Blue)",
  alt_tsuri_pinku: "Tsuri Eyes (Pink)",
  alt_tsuri_aka: "Tsuri Eyes (Red)",
  alt_tsuri_kimidori: "Tsuri Eyes (Lime)",
  alt_tsuri_kiiro: "Tsuri Eyes (Yellow)",
  alt_tsuri_silver: "Tsuri Eyes (Silver)",
  alt_sankaku_mizuiro: "Triangle Eyes (Light Blue)",
  alt_sankaku_ao: "Triangle Eyes (Blue)",
  alt_sankaku_pink: "Triangle Eyes (Pink)",
  alt_sankaku_aka: "Triangle Eyes (Red)",
  alt_sankaku_kimidori: "Triangle Eyes (Lime)",
  alt_sankaku_kiiro: "Triangle Eyes (Yellow)",
  alt_sankaku_silver: "Triangle Eyes (Silver)",
  alt_oddoai_1: "Odd Eye 1",
  alt_oddoai_2: "Odd Eye 2",
  alt_sanpakugan: "Three White Eyes",
  alt_kyomu: "Void Eyes",
  alt_nikoo: "Niko Eyes",
  alt_bou: "Line Eyes",
  alt_bikkuri: "Surprised Eyes",

  // Nose
  alt_nashi: "None",
  alt_ari: "Present",
  alt_ari_chotto_shita: "Present (Slightly Lower)",
  alt_doragon_you_nashi: "Dragon Style (None)",
  alt_doragon_you_hana_ari: "Dragon Style (Present)",
  alt_doragon_you_hana_chotto_shita: "Dragon Style (Slightly Lower)",

  // Mouth
  alt_magao: "Neutral",
  alt_mu: "Pout",
  alt_osumashi: "Prim",
  alt_nikott: "Smile",
  alt_nyaan: "Nyaa",
  alt_yaeba_nyaan: "Fanged Nyaa",
  alt_tehepero: "Tehepero",
  alt_sankaku: "Triangle",
  alt_gyaku_sankaku: "Inverted Triangle",
  alt_puchi_egao: "Small Smile",
  alt_egao: "Smile",
  alt_anguri: "Open Mouth",
  alt_nyaha: "Nyah",
  alt_gizappa: "Sharp Teeth",
  alt_gununu: "Grr...",
  alt_n_point: "N.",
  alt_fu: "Hmph",
  alt_hoe: "Howl",

  // Eyebrows
  alt_eyebrows_futsuu: "Normal",
  alt_agari: "Raised",
  alt_sagari: "Lowered",
  alt_oko: "Angry",
  alt_aori: "Provocative",
  alt_kiri: "Sharp",
  alt_kiri_shita: "Sharp (Slightly Lower)",
  alt_maro: "Round",
  alt_maro_shita: "Round (Slightly Lower)",
  alt_futo: "Thick",

  // Hair
  alt_hair_nashi: "None",
  alt_hair_futsuu: "Normal",
  alt_pattun: "Straight cut",
  alt_sara: "Smooth",
  alt_moko: "Moko",
  alt_yokonagashi: "Side swept",
  alt_hoso: "Thin",
  alt_hidarime_kakure: "Left eye covered",
  alt_migime_kakure: "Right eye covered",
  alt_ryome_kakure: "Both eyes covered",
  alt_yokogami_fuwa: "Side hair (fluffy)",
  alt_yokogami_kuri: "Side hair (curly)",
  alt_yokogami_roll: "Side hair (roll)",
  alt_yokogami_sara: "Side hair (smooth)",
  alt_meri_you_moko: "Mer moko",
  alt_tategami: "Mane",
  alt_kinpatsu: "Blonde",
  alt_ginpatsu: "Silver",
  alt_dora_kinpatsu: "Dragon blonde",
  alt_dora_ginpatsu: "Dragon silver",
  alt_ikkaku: "Single horn",

  // Outfits
  alt_outfit_nashi: "None",
  alt_scarf_red: "Scarf (Red)",
  alt_scarf_blue: "Scarf (Blue)",
  alt_scarf_black: "Scarf (Black)",
  alt_mizugi_mizuiro: "Swimsuit (Light blue)",
  alt_mizugi_green: "Swimsuit (Green)",
  alt_mizugi_purple: "Swimsuit (Purple)",
  alt_muffler_red: "Muffler (Red)",
  alt_muffler_blue: "Muffler (Blue)",
  alt_muffler_yellow: "Muffler (Yellow)",
  alt_muffler_green: "Muffler (Green)",
  alt_muffler_purple: "Muffler (Purple)",
  alt_muffler_white: "Muffler (White)",
  alt_muffler_gray: "Muffler (Gray)",
  alt_dress_red: "Dress (Red)",
  alt_dress_blue: "Dress (Blue)",
  alt_dress_black: "Dress (Black)",
  alt_dress_pink: "Dress (Pink)",
  alt_dress_mizuiro: "Dress (Light blue)",
  alt_dress_purple: "Dress (Purple)",
  alt_dress_green: "Dress (Green)",
  alt_manto: "Cape",
  alt_kizoku_red: "Noble (Red)",
  alt_kizoku_mizuiro: "Noble (Light blue)",
  alt_kizoku_purple: "Noble (Purple)",
  alt_kizoku_orange: "Noble (Orange)",
  alt_kizoku_green: "Noble (Green)",
  alt_kizoku_black: "Noble (Black)",
  alt_cape_orange: "Cape (Orange)",
  alt_cape_yellow: "Cape (Yellow)",
  alt_cape_mizuiro: "Cape (Light blue)",
  alt_cape_purple: "Cape (Purple)",
  alt_cape_pink: "Cape (Pink)",
  alt_fuwaeri_white: "Fluffy collar (White)",
  alt_fuwaeri_black: "Fluffy collar (Black)",
  alt_sorcier_robe_red: "Sorcier robe (Red)",
  alt_sorcier_robe_blue: "Sorcier robe (Blue)",
  alt_sorcier_poncho_red: "Sorcier poncho (Red)",
  alt_sorcier_poncho_pink: "Sorcier poncho (Pink)",
  alt_sorcier_poncho_blue: "Sorcier poncho (Blue)",
  alt_sorcier_poncho_mizuiro: "Sorcier poncho (Light blue)",
  alt_sorcier_poncho_black: "Sorcier poncho (Black)",
  alt_sorcier_robe_green: "Sorcier robe (Green)",
  alt_sorcier_robe_purple: "Sorcier robe (Purple)",
  alt_yamato_kimono_kurenai: "Yamato kimono (Crimson)",
  alt_yamato_kimono_momo: "Yamato kimono (Peach)",
  alt_yamato_kimono_daidai: "Yamato kimono (Orange)",
  alt_yamato_kimono_uguisu: "Yamato kimono (Warbler)",
  alt_yamato_kimono_mizuiro: "Yamato kimono (Light blue)",
  alt_suit_black: "Suit (Black)",
  alt_suit_white: "Suit (White)",
  alt_marine_sailor_white: "Marine sailor (White)",
  alt_marine_sailor_black: "Marine sailor (Black)",
  alt_yamato_suzu_kurenai: "Yamato bell (Crimson)",
  alt_yamato_suzu_ao: "Yamato bell (Blue)",

  // Accessories
  alt_accessories_nashi: "None",
  alt_deka_ribbon_pink: "Large ribbon (Pink)",
  alt_deka_ribbon_mizuiro: "Large ribbon (Light blue)",
  alt_deka_ribbon_purple: "Large ribbon (Purple)",
  alt_katyusha_pink: "Headband (Pink)",
  alt_katyusha_mizuiro: "Headband (Light blue)",
  alt_katyusha_black: "Headband (Black)",
  alt_brooch_red: "Brooch (Red)",
  alt_brooch_blue: "Brooch (Blue)",
  alt_brooch_green: "Brooch (Green)",
  alt_ribbon_red: "Ribbon (Red)",
  alt_ribbon_blue: "Ribbon (Blue)",
  alt_ribbon_gray: "Ribbon (Gray)",
  alt_ribbon_black: "Ribbon (Black)",
  alt_flower_shiro: "Flower (White)",
  alt_flower_pink: "Flower (Pink)",
  alt_flower_mizuiro: "Flower (Light blue)",
  alt_yamato_ume_kurenai: "Yamato plum (Crimson)",
  alt_yamato_ume_kuro: "Yamato plum (Black)",
  alt_kazarihimo_kurenai: "Decorative cord (Crimson)",
  alt_kazarihimo_kon: "Decorative cord (Navy)",
  alt_oukan_red: "Crown (Red)",
  alt_oukan_blue: "Crown (Blue)",
  alt_oukan_purple: "Crown (Purple)",
  alt_oukan_green: "Crown (Green)",
  alt_oukan_yellow: "Crown (Yellow)",
  alt_oukan_pink: "Crown (Pink)",
  alt_oukan_black: "Crown (Black)",
  alt_casquette_red: "Casquette (Red)",
  alt_casquette_blue: "Casquette (Blue)",
  alt_casquette_green: "Casquette (Green)",
  alt_casquette_white: "Casquette (White)",
  alt_silkhat_red: "Silk hat (Red)",
  alt_silkhat_blue: "Silk hat (Blue)",
  alt_fennec_beret_red: "Fennec beret (Red)",
  alt_fennec_beret_blue: "Fennec beret (Blue)",
  alt_fennec_beret_gray: "Fennec beret (Gray)",
  alt_vivid_knit_red: "Vivid knit (Red)",
  alt_vivid_knit_blue: "Vivid knit (Blue)",
  alt_vivid_knit_yellow: "Vivid knit (Yellow)",
  alt_vivid_knit_green: "Vivid knit (Green)",
  alt_vivid_knit_black: "Vivid knit (Black)",
  alt_tongari_boushi_black: "Pointed hat (Black)",
  alt_tongari_boushi_white: "Pointed hat (White)",
  alt_tongari_boushi_pink: "Pointed hat (Pink)",
  alt_tongari_boushi_mizuiro: "Pointed hat (Light blue)",
  alt_biidama_pink: "Marble (Pink)",
  alt_biidama_blue: "Marble (Blue)",
  alt_biidama_black: "Marble (Black)",
  alt_usamimi_red: "Rabbit ears (Red)",
  alt_usamimi_blue: "Rabbit ears (Blue)",
  alt_usamimi_green: "Rabbit ears (Green)",
  alt_usamimi_white: "Rabbit ears (White)",
  alt_usamimi_black: "Rabbit ears (Black)",
  alt_yotsuba: "Four-leaf clover",
  alt_pilot_goggle: "Pilot goggles",

  // Options
  alt_options_nashi: "None",
  alt_shiromaru: "White circle",
  alt_shiro_sankaku: "White triangle",
  alt_onaka_kemo: "Belly (Kemo)",
  alt_onaka_dora: "Belly (Dragon)",
  alt_hoppe_pink: "Cheeks (Pink)",
  alt_hoppe_orange: "Cheeks (Orange)",
  alt_megane: "Glasses",
  alt_maru_megane: "Round glasses",
  alt_maru_megane_sho: "Small round glasses",
  alt_monocle_migi: "Monocle (Right)",
  alt_monocle_hidari: "Monocle (Left)",
  alt_moyou_1: "Pattern 1",
  alt_moyou_2: "Pattern 2",
  alt_namida_bokuro: "Tear mole",
  alt_kizu_sho: "Scar (Small)",
  alt_kizu_dai: "Scar (Large)",
  alt_third_eye_aka: "Third eye (Red)",
  alt_third_eye_murasaki: "Third eye (Purple)",
  alt_third_eye_silver: "Third eye (Silver)",

  // Footer
  footer_original: "Original Concept by: <a href=\"https://x.com/BAYACHAO\" target=\"_blank\" rel=\"noopener noreferrer\">BAYACHAO</a>",
  footer_plus: "+ (Plus) Version by: <a href=\"https://x.com/KaiVster\" target=\"_blank\" rel=\"noopener noreferrer\">KaiVs</a>",
  footer_copyright: "&copy; 2025 KaiVs. All Rights Reserved | &copy; 2018 BAYACHAO. All Rights Reserved"
};